image: infinityrefactoring/maven:3.5

cache:
  key: maven-dependencies
  policy: pull
  paths:
    - /root/.m2/repository

stages:
  - build
  - validation
  - test
  - package
  - deploy

build:
  stage: build
  cache:
    key: target
    policy: push
    paths:
      - ./target
  script:
    - mvn compile

validate_version:
  stage: validation
  before_script:
    - chmod +x ./ivg/ivg
    - IVG_PATH="$(pwd)/ivg"
    - PATH="$IVG_PATH:$PATH"
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$GITLAB_USER_NAME"
  script:
    - ivg validate

test:
  stage: test
  script:
    - mvn clean test

package:
  stage: package
  cache:
    key: target
    policy: push
    paths:
      - ./target
  script:
    - mvn package -DskipTests
  only:
    - dev
    - master

deploy_to_staging:
  stage: deploy
  script:
    - echo "Deploing to Staging..."
    - echo "Deployed to Staging with success"
  only:
    - dev

deploy_to_oss:
  stage: deploy
  before_script:
    - gpg2 --import --batch --passphrase "$MAVEN_GPG_PASSPHRASE" <<< "$MAVEN_GPG_KEY_VALUE"
  script:
    - mvn -P oss-release -DskipTests deploy
  only:
    - master

deploy_to_production:
  stage: deploy
  script:
    - echo "Deploing to Production..."
    - echo "Deployed to Production with success"
  only:
    - master