image:
  name: infinityrefactoring/maven:3.5
  entrypoint: [""]

cache:
  paths:
    - maven.repository/

variables:
  SSH_USER: git
  ORIGIN: $SSH_USER@$SSH_HOST:$GIT_ORIGIN_REPOSITORY
  MAVEN_OPTS: "-Dmaven.repo.local=maven.repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN"

before_script:
  - /usr/local/bin/docker-entrypoint

stages:
  - setup
  - verify
  - test
  - package
  - deploy

version_update:
  stage: setup
  script:
    - ivg generate --push --push-origin=$ORIGIN --push-branch=HEAD:$CI_COMMIT_REF_NAME --autosquash=false --use-error-exit-code
  except:
    - develop
    - master

version_validation:
  stage: verify
  script:
    - ivg validate
  only:
    - develop
    - master

code_quality:
  stage: verify
  cache:
    paths:
      - maven.repository/
      - /root/.sonar/cache
  variables:
    SONAR_BRANCH_NAME: $CI_COMMIT_REF_NAME
  script:
    - mvn-sonar
  environment:
    name: code-quality
    url: $SONAR_DASHBOARD_URL

test:
  stage: test
  script:
    - mvn clean test

package:
  stage: package
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/*.jar
      - target/*.war
    expire_in: 6 mos 1 day
  only:
    - develop
    - master

deploy:staging_maven_central:
  stage: deploy
  environment:
    name: staging-artifact/$CI_PIPELINE_ID
    url: https://oss.sonatype.org/content/repositories/snapshots/com/infinityrefactoring/gitlab-ci-test
  script:
    - echo "mvn -P oss-release -DskipTests deploy"
  dependencies:
    - package
  only:
    - develop

deploy:maven_central:
  stage: deploy
  when: manual
  environment:
    name: artifact/$CI_PIPELINE_ID
    url: https://search.maven.org/search?q=g:com.infinityrefactoring%20AND%20a:gitlab-ci-test
  before_script:
    - chmod +x ./create-github-release
  script:
    - version=$(ivg get-version --quiet)
    - echo "mvn -P oss-release -DskipTests deploy"
    - git tag -a "v$version" -m "Version $version"
    - git push $ORIGIN $version
    - create-github-release
  dependencies:
    - package
  only:
    - master