image: infinityrefactoring/maven:3.5

cache:
  paths:
    - /root/.m2/repository

stages:
  - test
  - package
  - deploy

test:
  stage: test
  script:
    - mvn clean test

package:
  stage: package
  cache:
    key: target
    policy: push
    paths:
      - ./target
  script:
    - mvn package -DskipTests

deploy:
  stage: deploy
  before_script:
    - gpg2 --import --batch --passphrase "$MAVEN_GPG_PASSPHRASE" <<< "$MAVEN_GPG_KEY_VALUE"
  script:
    - mvn -P oss-release -DskipTests deploy